swagger: "2.0"
info:
  title: Dictionary Backend API
  version: 1.0.0
paths:
  /lookup:
    get:
      summary: Perform a lookup
      responses:
        200:
          description: Successful lookup
          schema:
            type: object
  /login:
    get:
      summary: Render login page
      responses:
        200:
          description: Successful response
    post:
      summary: Authenticate user
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: username
          type: string
          required: true
        - in: formData
          name: password
          type: string
          required: true
      responses:
        200:
          description: Successful authentication
        302:
          description: Redirect to login page
  /:
    get:
      summary: Render home page
      security:
        - session: []
      responses:
        200:
          description: Successful response
securityDefinitions:
  session:
    type: apiKey
    name: Authorization
    in: header
