swagger: "2.0"
info:
  title: MongoDB API
  version: 1.0.0
paths:
  /api/data:
    get:
      summary: Retrieve data from MongoDB
      responses:
        200:
          description: Successful response
          schema:
            type: object
  /api/data/{id}:
    get:
      summary: Retrieve data by ID from MongoDB
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: The ID of the data to retrieve
      responses:
        200:
          description: Successful response
          schema:
            type: object
securityDefinitions:
  apiKey:
    type: apiKey
    name: Authorization
    in: header
