swagger: "2.0"
info:
  title: Authentication API
  version: 1.0.0
paths:
  /login:
    post:
      summary: Authenticate user
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: username
          type: string
          required: true
        - in: formData
          name: password
          type: string
          required: true
      responses:
        200:
          description: Successful authentication
        302:
          description: Redirect to login page
securityDefinitions:
  session:
    type: apiKey
    name: Authorization
    in: header
