swagger: '2.0'
info:
  title: Authentication API
  version: 1.0.0
host: localhost:3000
basePath: /
schemes:
  - http
paths:
  /login:
    post:
      summary: Authenticate user login
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: username
          in: formData
          description: User's username
          required: true
          type: string
        - name: password
          in: formData
          description: User's password
          required: true
          type: string
      responses:
        '200':
          description: Successful login
        '401':
          description: Unauthorized
  /logout:
    post:
      summary: Logout the authenticated user
      responses:
        '200':
          description: Successful logout
  /status:
    get:
      summary: Get the authentication status of the current user
      responses:
        '200':
          description: Successful operation
          schema:
            type: object
            properties:
              authenticated:
                type: boolean
  /save:
    post:
      summary: Save a word and its definition
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: word
          in: formData
          description: Word to save
          required: true
          type: string
        - name: definition
          in: formData
          description: Definition of the word
          required: true
          type: string
      responses:
        '200':
          description: Successful operation
        '401':
          description: Unauthorized
securityDefinitions:
  session:
    type: apiKey
    name: session
    in: header
security:
  - session: []
